[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "3.9.19"
chainlit = "0.7.700"
cohere = "4.37"
openai = "1.3.5"
tiktoken = "0.5.1"
python-dotenv = "1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
